/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        cream: "var(--bg)",
        surface: "var(--surface)",
        "surface-elevated": "var(--surface-elevated)",
        "surface-muted": "var(--surface-muted)",
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-50": "var(--primary-50)",
        "primary-100": "var(--primary-100)",
        mint: "var(--mint)",
        "mint-light": "var(--mint-light)",
        coral: "var(--coral)",
        "coral-light": "var(--coral-light)",
        gold: "var(--gold)",
        ink: "var(--ink)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        "ink-4": "var(--ink-4)",
        "ink-on-dark": "var(--ink-on-dark)",
        line: "var(--line)",
        "line-2": "var(--line-2)",
        "line-strong": "var(--line-strong)",
      },
      fontFamily: {
        sans: ["DM Sans", "system-ui", "sans-serif"],
        mono: ["DM Mono", "monospace"],
      },
      fontSize: {
        display: ["56px", { lineHeight: "1.05", letterSpacing: "-1.2px" }],
        title: ["38px", { lineHeight: "1.15", letterSpacing: "-1px" }],
        heading: ["22px", { lineHeight: "1.3", letterSpacing: "-0.4px" }],
        "body-lg": ["17px", { lineHeight: "1.45", letterSpacing: "-0.1px" }],
        body: ["15px", { lineHeight: "1.5" }],
        small: ["13px", { lineHeight: "1.5" }],
        eyebrow: ["11px", { lineHeight: "1", letterSpacing: "0.14em" }],
      },
      borderRadius: {
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        "card-active": "var(--shadow-card-active)",
      },
      spacing: {
        "s-1": "4px",
        "s-2": "8px",
        "s-3": "16px",
        "s-4": "24px",
        "s-5": "32px",
        "s-6": "48px",
        "s-7": "64px",
        "s-8": "80px",
      },
    },
  },
  plugins: [],
};
